import { useState, useEffect } from 'react'
import './Terms.css'
import { NavLink } from 'react-router-dom'
import useWindowDimensions from '../hooks/getWindowDimensions';
import { useNavigate } from 'react-router-dom'

function Terms() {
  const navigate = useNavigate();
  const { height, width } = useWindowDimensions();

  useEffect(() => {
    if (width > 476) 
        navigate("/");
  });

  return (
    <div className="terms-page">
        <div className="nav-container">
        <NavLink to="/Start"><img src="logo-purple.png" alt="logo" /></NavLink>
        </div>
        <h1>DASH E-RIDES Termeni &amp; Condiții </h1>
        <h1 className="h1-2">ROMÂNIA</h1>
        <h1 className="h1-3">VĂ MULŢUMIM PENTRU ALEGEREA DASH E-RIDES!</h1>
        <p>Prezentele condiții („Termeni”) reglementează utilizarea dvs. a diverselor produse, servicii, aplicații și produse software pe care le punem la dispoziție (în ansamblul lor, „Serviciile” noastre). Acestea sunt furnizate de compania DASH E-RIDES S.R.L. Prin utilizarea Serviciilor noastre (inclusiv utilizarea Aplicației sau crearea unui cont de utilizator, de exemplu), sunteți de acord cu acești Termeni, încheindu-se astfel un acord între noi. Pentru a utiliza Serviciile, trebuie să aveți vârsta legală pentru a încheia contracte cu caracter obligatoriu, așadar vă rugăm să citiți cu atenție acești Termeni. De asemenea, vă asigurați că aveți autoritatea de a accepta acești Termeni.</p>
        <p>În cazul în care nu sunteți de acord cu acești Termeni, nu puteți folosi Serviciile noastre. Rețineți că putem aduce modificări acestor Termeni periodic, iar versiunea revizuită va deveni valabilă atunci când este publicată pe acest site web. Cu toate acestea, veți putea consulta orice versiune revizuită a acestor Termeni înainte ca aceasta să devină valabilă. Termenii revizuiți vor înlocui orice versiuni anterioare. Chiar dacă vom emite notificări prealabile cu privire la revizuirile semnificative, vă recomandăm să verificați în mod regulat acești Termeni, deoarece continuarea utilizării Serviciilor noastre după modificări constituie acceptul dvs. față de acestea. Acești Termeni anulează orice acorduri sau înțelegeri anterioare pe care le-am putea avea cu dvs. cu privire la Servicii. Desigur, aveți dreptul să încetați utilizarea Serviciilor noastre în orice moment, iar noi putem rezilia acești Termeni sau utilizarea dvs. a oricăror Servicii, sau putem înceta furnizarea și refuza accesul la anumite Servicii, la discreția noastră (cu mențiunea că, în cazul în care nu sunteți de acord sau doriți să solicitați astfel de rezilieri sau încetări din partea noastră, vă rugăm să ne contactați la adresa de suport contact@ridedash.eu cu detaliile relevante). Termenii specifici care se aplică abonamentelor pentru Serviciile noastre sunt prezentate mai jos, incluzând perioadele de notificare suplimentare înainte de a efectua modificări legate de prețuri sau de alți termeni importanți ai abonamentului. </p>
        <p>Vă rugăm să aveți în vedere că orașul dvs. de reședință poate impune termeni și condiții suplimentare, pe care trebuie să le cunoașteți atunci când utilizați Serviciile noastre. Vă invităm să verificați lista corespunzătoare pentru a determina dacă există astfel de condiții pentru orașul dvs. </p>
        <h2>1. Ce oferă DASH E-RIDES</h2>
        <p>DASH E-RIDES a fost înființată cu viziunea simplă că fiecare comunitate merită să beneficieze de acces la mobilitate inteligentă și convenabilă. Misiunea noastră este să transformăm această viziune în realitate. Echipa noastră lucrează în mod constant la îmbunătățirea Serviciilor noastre, iar din data menționată anterior, acestea includ biciclete electrice și facilitățile de parcare aferente. În acești Termeni, ne referim adesea la aceste elemente individual ca la un "Produs" sau colectiv ca la "Produse". Serviciile noastre cuprind, de asemenea, aplicația mobilă (denumită "Aplicația"), toate celelalte echipamente conexe, întreținerea, încărcarea, personalul nostru, site-urile noastre web și orice alte informații, tehnologie și servicii furnizate sau puse la dispoziție în orice alt mod la latitudinea noastră. Furnizăm Serviciile noastre ca o opțiune de confort pentru cei care sunt capabili și îndeplinesc condițiile pentru a le utiliza, în timp ce alternativele de transport public și privat sunt disponibile atât pentru dvs., cât și pentru publicul larg.</p>
        <h2>2. Contul dvs. de utilizator Dash</h2>
        <p><span className="bold">Configurarea unui cont:</span> Pentru a utiliza Serviciile noastre, este necesar să creați un cont. Pentru aceasta, va trebui să furnizați un card de debit sau de credit valid sau o altă metodă de plată aprobată, împreună cu data de expirare (aceste informații sunt transmise unui procesator de plăți extern - nu le primim și nu le stocăm). De asemenea, veți fi solicitați să furnizați alte informații relevante pentru Produsul specific pe care doriți să-l utilizați. Furnizarea acestor informații este esențială pentru a vă putea oferi accesul la Serviciile noastre. </p>
        <p>Crearea de conturi și opțiuni alternative de plată sunt disponibile pentru unele dintre produsele și serviciile noastre, în funcție de disponibilitatea lor în zona dvs., cum ar fi DASH E-RIDES. Este important ca informațiile furnizate să fie veridice, precise, complete și actualizate, deoarece acestea sunt esențiale pentru funcționarea corespunzătoare a serviciilor. La momentul creării contului, vă rugăm să generați un nume de utilizator și o parolă puternică, pe care să nu le dezvăluiți nimănui. Contul dvs. este personal și nu trebuie să fie utilizat de către alte persoane. Sunteți responsabil pentru toate activitățile desfășurate în cadrul contului. </p>
        <p>Dacă bănuiți că contul dvs. a fost utilizat fără autorizare, vă rugăm să ne informați imediat.</p>
        <p><span className="bold">Frauda:</span> Abordăm problema fraudei cu seriozitate, în interesul dvs. și al nostru. Puteți utiliza doar o metodă de plată pentru care aveți dreptul legal să o utilizați și ne autorizați să efectuăm tranzacții pe această metodă pentru orice costuri aferente utilizării Serviciilor noastre. Dacă există suspiciuni cu privire la veridicitatea, completitudinea sau corectitudinea informațiilor furnizate, ne rezervăm dreptul de a suspenda sau rezilia contul dvs. până când problema este clarificată. În acest interval, accesul la unele sau toate Serviciile noastre poate fi restricționat temporar sau permanent. </p>
        <h2>3. Utilizarea Aplicației și a Serviciilor noastre</h2>
        <p>Prin intermediul Aplicației, aveți posibilitatea să localizați, să rezervați și să închiriați Produsele noastre disponibile. Vă rugăm să fiți conștienți că din considerente legate de siguranță și din motive operationale, ne rezervăm dreptul de a aproba sau respinge cererile de rezervare. În cazul în care solicitarea dvs. de rezervare prin Aplicație este respinsă, veți primi rambursarea corespunzătoare, presupunând că metoda de plată a fost debitată inițial. Dacă apar discrepanțe în ceea ce privește prețurile afișate în Aplicație, indiferent de motivele acestora, ne rezervăm dreptul de a respinge o rezervare și de a vă rambursa sumele corespunzătoare. </p>
        <p className="bold">Câteva reguli esențiale:</p>
        <p>Este obligatoriu să fiți unicul utilizator al Serviciilor noastre, iar în anumite cazuri pot exista reguli suplimentare, fie incluse în acești Termeni, fie comunicate în alt mod. </p>
        <p>Pentru a utiliza Serviciile noastre, trebuie să aveți cel puțin 18 ani sau vârsta legală de majorat, dacă aceasta este mai mare. </p>
        <p>Trebuie să puteți utiliza Produsele noastre în mod competent și să aveți cunoștințe despre modul de funcționare a acestora, precum și capacitatea fizică necesară pentru utilizare. În plus, trebuie să fiți conștienți că condițiile meteorologice pot influența siguranța și trebuie să acționați în consecință, de exemplu, adaptând distanța de frânare în caz de ploaie. De asemenea, trebuie să înțelegeți că nu oferim indicații privind traseul sau recomandări, iar ruta pe care o alegeți este la latitudinea dvs. </p>
        <p>Deși facem eforturi pentru a vă informa cu privire la legile locale care se aplică utilizării Produselor noastre, este responsabilitatea dvs. să vă familiarizați cu aceste legi și să le respectați atunci când utilizați Serviciile noastre. Asigurați-vă că nu utilizați Serviciile noastre în zone interzise și că respectați regulile privind utilizarea pe trotuar, parcare (evitați blocarea traficului pietonal, de exemplu) și consumul de alcool/droguri în timpul utilizării. </p>
        <p>Este interzis să încercați să spargeți, vandalizați sau să obțineți acces neautorizat la Serviciile noastre. </p>
        <p>Minorii sub vârsta de 18 ani nu au dreptul să folosească bicicletele electrice. </p>
        <p><span className="bold">Siguranța este foarte importantă!</span> Vă recomandăm să purtați întotdeauna o cască certificată CE atunci când utilizați Produsele noastre, preferabil una aprobată de organizațiile Snell, CPSC, ANSI sau ASTM. Asigurați-vă că cască este dimensionată, montată și fixată conform instrucțiunilor producătorului. Rețineți că legile locale pot impune purtarea căștii în anumite zone, deci trebuie să o utilizați obligatoriu în astfel de cazuri. Dacă alegeți să nu purtați cască și suferiți vătămări, vă asumați responsabilitatea pentru acest risc, iar noi nu suntem responsabili (cu excepția situațiilor în care suntem direct implicați în cauza vătămării). </p>
        <p>E important să vă asigurați că Produsul pe care îl utilizați este în stare bună de funcționare. Faceți o verificare de siguranță înainte de a-l utiliza, incluzând: </p>
        <p>Verificarea generală a stării Produsului, precizia roților sau, în cazul bicicletelor, a stării cauciucurilor. </p>
        <p>Testarea funcționalității frânelor și a sistemului de iluminare. </p>
        <p>Verificarea corectitudinii montării și fixării scaunului, pedalelor și a coșului, dacă e cazul. </p>
        <p>Asigurarea că bateria este încărcată adecvat. </p>
        <p>Observarea oricăror semne de deteriorare sau uzură excesivă și necesitatea oricărei operațiuni de mentenanță. </p>
        <p>Dacă observați orice defecțiuni sau probleme la Produs înainte de utilizare, vă rugăm să ne informați imediat la adresa de suport contact@ridedash.eu. Nu utilizați Produsul și rezervați un altul în schimb. Dacă observați probleme în timpul utilizării, întrerupeți călătoria în siguranță și raportați problemele cât mai curând posibil. Neprezentarea acestor probleme poate duce la atribuirea dvs. a responsabilității pentru eventuale costuri asociate. </p>
        <p className="bold">Reguli suplimentare pentru Produsele electrice: </p>
        <p>Produsele electrice nu sunt întotdeauna disponibile și sunt disponibile într-un număr limitat. </p>
        <p>Acestea necesită încărcarea periodică a bateriilor pentru funcționare. Nivelul de încărcare scade pe măsură ce le utilizați, iar acesta poate varia în funcție de factori precum vremea, condițiile de drum și tipul de Produs. </p>
        <p>Vă revine responsabilitatea să monitorizați nivelul de încărcare al Produsului închiriat și să luați decizii în cunoștință de cauză cu privire la utilizare în funcție de starea bateriei. Chiar dacă facem eforturi pentru a asigura un nivel de încărcare adecvat pentru utilizarea generală, nu putem garanta că Produsul electric va avea întotdeauna suficientă încărcare pentru a vă duce unde doriți. </p>
        <h2>4. Fiți în siguranță când utilizați Produsele noastre! </h2>
        <p>Dorim să vă asigurăm o experiență sigură pentru dumneavoastră și pentru ceilalți participanți la trafic, și pentru aceasta impunem anumite reguli. Pe lângă necesitatea de a fi atent și de a folosi discernământul, există câteva restricții importante: </p>
        <p>Nu transportați obiecte, cum ar fi serviete sau genți, și evitați să utilizați dispozitive precum telefoane mobile sau alte echipamente portabile care pot împiedica sau pune în pericol utilizarea în condiții de siguranță a Produselor. De exemplu, nu trimiteți mesaje în timpul utilizării Produselor. </p>
        <p>Nu presupuneți întotdeauna că există un traseu special sau o pistă pentru utilizarea Produselor noastre; fiți vigilenți în trafic și în prezența vehiculelor, deoarece nu suntem responsabili pentru acțiunile șoferilor. </p>
        <p>Utilizarea Serviciilor noastre în stare de ebrietate, sub influența drogurilor sau a altor substanțe este strict interzisă. </p>
        <p>Nu permiteți transportul altor persoane sau animale în timp ce utilizați Produsele noastre. </p>
        <p>Nu blocați sau încuiați Produsul cu dispozitive de blocare care nu sunt deținute de noi, deoarece nu vom putea să-l deblocăm. </p>
        <p>Vă rugăm să nu lăsați un Produs într-o locație sau poziție inaccesibilă pentru noi, deoarece acest lucru poate crea dificultăți în recuperarea Produsului, iar în astfel de cazuri vă putem taxa cu până la 1880 RON pentru costurile asociate. </p>
        <p>Nu utilizați Serviciile noastre pentru activități care depășesc scopul de utilizare prevăzut pentru un Produs. Evitați cursele, plimbările pe teren accidentat, cascadoriile sau trucurile, precum și utilizarea Produselor în medii neadecvate, cum ar fi drumurile neamenajate sau zonele inundate. Toate acestea pot duce la deteriorarea Produselor noastre. </p>
        <p>Nu folosiți Serviciile noastre în scopuri comerciale, cum ar fi închirierea Produselor sau orice altă utilizare comercială, precum publicitate, servicii de ridesharing sau livrare de alimente. </p>
        <p>În niciun caz nu utilizați Serviciile noastre în scopul încălcării legislației în vigoare. </p>
        <p>Aceste reguli au ca scop principal siguranța și bunul mers al utilizării Produselor noastre, și vă rugăm să le respectați cu atenție. </p>
        <h2>5. Tratați Produsele noastre ca și cum ar fi ale dvs.! </h2>
        <p><span className="bold">Utilizarea responsabilă.</span> Este important ca toți utilizatorii să trateze Produsele noastre cu respect, pentru a le menține disponibile și într-o stare bună. Rețineți că acestea nu sunt indestructibile, așadar vă rugăm să le tratați cu grijă atunci când le folosiți. Toate Produsele au limite de greutate, în general de 120 kg, dar coșurile frontale ale bicicletelor au o limită de 5 kg. Utilizați-le cu prudență, mai ales atunci când transportați încărcătură, evitând să vă blocați câmpul vizual, de exemplu, nu punând obiecte mari în coșul frontal al bicicletei.</p>
        <p><span className="bold">Daune.</span> Vă rugăm să returnați fiecare Produs în aceeași stare în care l-ați primit, cu excepția uzurii normale. Dacă un Produs suferă daune din cauza dumneavoastră (accidental sau intenționat) sau dacă nu îl returnați într-un mod corespunzător și acesta se deteriorează, veți fi responsabil pentru costurile asociate reparării sau înlocuirii. Aceste costuri pot ajunge până la 8.260 RON pentru bicicletele electrice și se stabilesc pe baza evaluării costurilor. Aceleași taxe se aplică pentru orice Produs care nu este returnat în termen de 48 de ore de la închiriere, și este considerat pierdut sau furat. În anumite circumstanțe, ne rezervăm dreptul de a iniția acțiuni legale împotriva dumneavoastră și de a vă face responsabil pentru valoarea integrală a Produsului. </p>
        <p><span className="bold">Perioade de închiriere.</span> Aveți dreptul să închiriați un Produs pentru o perioadă de până la 24 de ore. Vă rugăm să monitorizați timpul și să returnați Produsul înainte de expirarea perioadei de închiriere. Recuperarea Produsului. Dacă nu puteți returna un Produs într-o zonă valabilă și solicitați preluarea acestuia de către noi, vă putem taxa o taxă de preluare de până la 520 RON. Dacă abandonați un Produs, veți fi responsabil pentru toate taxele asociate până la momentul recuperării, plus o taxă de servicii de până la 520 RON, în funcție de timpul și efortul necesare pentru recuperare. În cazul în care nu sunteți de acord cu oricare dintre aceste taxe, aveți posibilitatea să ne contactați la contact@ridedash.eu pentru a le contesta. </p>
        <p><span className="bold">Accidente sau daune generale.</span> Vă rugăm să ne anunțați imediat despre orice accident, avarie, daună sau vătămare corporală, precum și despre orice Produs pierdut sau furat. În cazul unui accident cu vătămare personală, daune materiale sau furt, trebuie să raportați incidentul imediat autorităților locale, iar în cazul altor incidente, să ne informați în termen de 24 de ore. </p>
        <h2>6. Termeni financiari </h2>
        <p className="bold">Închiriere și Abonamente: </p>
        <p>Vă rugăm să aveți în vedere că ne rezervăm dreptul de a modifica prețurile pentru Serviciile noastre, conform necesităților noastre sau în concordanță cu schimbările de pe piață. Prețul afișat include taxele, cum ar fi TVA și alte taxe guvernamentale aplicabile, și va fi debitat automat de pe metoda dvs. de plată preferată, în funcție de utilizarea dvs. Vom percepe și reține automat taxele aplicabile, în cazul în care legea o prevede. Toate plățile către noi sunt intermediare de un procesator de plăți terț, utilizând metoda de plată acceptată de acesta. Dacă sunteți în dezacord cu oricare dintre costurile pe care le-am aplicat contului dvs., vă rugăm să ne informați imediat după ce ați identificat problema. Pentru a rezolva orice contestație a costurilor, avem nevoie de detalii despre călătoria dvs., cum ar fi data și ora aproximativă a începutului și terminării acesteia. Noi urmăm o politică de a nu oferi rambursări pentru utilizarea Serviciilor noastre, cu excepția cazurilor în care decidem altfel. </p>
        <p className="bold">Coduri Promoționale: </p>
        <p>Periodic, oferim coduri promoționale, care pot fi supuse unor termeni și condiții specifice, furnizate în cadrul promoției respective. Vă rugăm să citiți cu atenție și să acceptați acești termeni dacă doriți să beneficiați de promoție. Trebuie să aveți în vedere că aceste promoții sunt oferte unice, pot fi rambursabile exclusiv prin intermediul aplicației noastre, și ne rezervăm dreptul de a le modifica sau anula în orice moment. Fiecare utilizator și cont pot folosi aceste coduri promoționale o singură dată, ele nu pot fi combinate cu alte oferte, au o perioadă de valabilitate specificată și nu pot fi transferate sau revândute. </p>
        <p className="bold">Abonamente: </p>
        <p>Dacă această opțiune este disponibilă în zona dvs., puteți accesa Serviciile noastre prin achiziționarea unui abonament lunar. Există câteva reguli adiționale pentru utilizarea abonamentelor: </p>
        <p>Abonamentul dvs. începe în momentul confirmării primei plăți și va fi taxat de către procesatorul nostru de plăți terțești în termen de 30 de zile de la autorizare. Abonamentul se va prelungi automat pentru perioada selectată la înregistrare (sau lunar, în cazul în care nu s-a specificat nicio perioadă). </p>
        <p>Prețul afișat este valabil la momentul înregistrării comenzii, dar ne rezervăm dreptul de a modifica prețurile în timp și nu garantăm protecție împotriva scăderilor de preț sau a ofertelor promoționale. Vom factura taxa automat în fiecare lună pe durata abonamentului. </p>
        <p>Oferim diverse planuri de membru, inclusiv perioade de probă gratuite, prețuri reduse pentru anumite perioade sau planuri promoționale speciale de la terți, care pot avea termeni și condiții diferite, specificate înainte de înregistrare. Unele dintre aceste oferte sunt furnizate de terțe părți, iar noi nu suntem responsabili pentru produsele și serviciile oferite de acestea. În cazul perioadelor de probă gratuite, unele companii de carduri de credit pot bloca temporar metoda de plată la prima plată. </p>
        <p>Rezervăm dreptul de a modifica, anula sau ajusta planurile de abonament pentru membri, cu notificare prealabilă în scris cu 30 de zile înainte de a face asta. Dacă nu sunteți de acord cu noile condiții, puteți anula abonamentul fără penalități, în loc să continuați cu termenii modificați sau ajustați. </p>
        <p>Putem anula abonamentul în orice moment, cu sau fără motive, prin notificare prealabilă în scris cu 30 de zile înainte. Aveți dreptul să faceți același lucru, dar dacă anulați în mijlocul unei perioade de abonament, nu veți primi o rambursare pentru lunile parțiale și puteți renunța la orice taxă de membru. În ambele cazuri, veți putea să utilizați Serviciile până la finalul perioadei pentru care ați plătit. Aceasta nu afectează drepturile dvs. de reziliere conform Secțiunii 7 de mai jos. De asemenea, putem anula abonamentul dacă nu plătiți sumele datorate sau dacă încălcați acești Termeni, fără a primi o rambursare pentru lunile parțiale și renunțând la orice taxă de membru. </p>
        <p>Abonamentul se va reînnoi automat la prețurile curente pentru aceeași perioadă ca durata inițială a membrilor. Va continua pe termen nedeterminat, cu excepția cazului în care îl anulați (fără penalități) înainte de expirarea perioadei curente de subscriere. Prețurile noastre, taxele și comisioanele pot varia în timp, deci prețurile pot diferi de la o perioadă de subscriere la alta. Ne rezervăm dreptul de a modifica prețurile abonamentului în orice moment, dar vă vom notifica în scris cu cel puțin 30 de zile înainte.</p>
        <h2>7. Drepturi de anulare ale consumatorilor pentru abonamente </h2>
        <p>De obicei, aveți opțiunea de a anula un abonament în termen de 14 zile de la data în care primiți confirmarea acceptării solicitării de abonare. Cu toate acestea, vă rugăm să fiți conștienți că începem furnizarea Serviciilor de abonament imediat după ce primiți această confirmare (prin înregistrarea pentru un abonament, ne solicitați să începem furnizarea acestor servicii) și, dacă decideți să anulați în timpul celor 14 zile, suma pe care ne-ați plătit (care va fi dedusă din orice rambursare pe care o primiți) va reflecta proporțional numărul de zile în care Serviciile de abonament au fost furnizate în luna respectivă. </p>
        <p>Pentru a anula un abonament, vă rugăm să ne contactați la adresa de e-mail contact@ridedash.eu și să ne furnizați informații precum numele, adresa și opțiunea comenzii dvs. Detalii suplimentare cu privire la drepturile consumatorului, inclusiv instrucțiuni despre cum să le exercitați, sunt incluse în confirmarea acceptării abonamentului dvs. Această secțiune nu afectează în niciun fel drepturile legale ale consumatorului. </p>
        <h2>8. Limitarea răspunderii </h2>
        <p>Atunci când folosim termenul "Părți exonerate" în acești Termeni, ne referim la următoarele: </p>
        <p>Noi, inclusiv afiliații noștri, sucursalele noastre, proprietarii acestora, managerii, funcționarii, angajații, directorii, agenții, reprezentanții, succesori, cesionarii, licențiatorii, distribuitorii, furnizorii și părțile terțe cu care avem acorduri pentru distribuirea, vânzarea sau promovarea Serviciilor. </p>
        <p>Municipalități și entități publice care ne-au acordat autorizații pentru furnizarea Serviciilor, inclusiv toți funcționarii aleși și numiți, oficialii, angajații și agenții acestora. </p>
        <p>În cazul în care accesați Serviciile utilizând o aplicație terță, site web, conținut, produs sau serviciu, respectiva parte terță și toți afiliații și sucursalele acesteia, precum și proprietarii, managerii, responsabilii, angajații, directorii, agenții, reprezentanții, succesori și cesionarii acesteia. </p>
        <p>Cu toate acestea, niciun aspect din acești Termeni nu va limita sau exclude răspunderea Părților exonerate față de dvs. în următoarele circumstanțe: </p>
        <p>Pentru deces sau vătămare corporală cauzată de neglijența Părților exonerate. </p>
        <p>Pentru declarații false. </p>
        <p>Pentru încălcarea oricăror drepturi prevăzute de legislația aplicabilă privind protecția consumatorilor (inclusiv, dar fără a se limita la Ordonanța de urgență a Guvernului 34/2014) care nu pot fi limitate sau excluse prin lege. </p>
        <p>Pentru orice altă răspundere care, prin lege, nu poate fi limitată sau exclusă. </p>
        <p>În conformitate cu această secțiune și în măsura permisă de legislația aplicabilă, dacă sunteți consumator (nu un client comercial), Părțile exonerate nu vor fi în nicio circumstanță răspunzătoare față de dvs. pentru pierderi indirecte, consecințiale sau pierderi de date. Dacă sunteți un client comercial, Părțile exonerate nu vor fi în nicio circumstanță răspunzătoare față de dvs. pentru pierderi indirecte, consecințele sau pierderi de profit, venituri, contracte, date, fond comercial sau alte pierderi similare. Orice răspundere pe care o avem pentru pierderile pe care le suferiți (indiferent dacă sunteți o companie sau un consumator) care decurg din acești Termeni va fi limitată la suma de 400 RON și se aplică strict pierderilor care erau previzibile în mod rezonabil. Pierderea sau deteriorarea este previzibilă dacă era evidentă că poate să apară sau dacă, la momentul încheierii contractului, atât noi, cât și dvs. știam că ar putea să apară. </p>
        <p>Părțile exonerate nu vor fi răspunzătoare sau responsabile pentru neîndeplinirea sau întârzierea în îndeplinirea oricăror obligații din acești Termeni ca urmare a evenimentelor care nu pot fi controlate în mod rezonabil de către noi, cum ar fi cazurile de forță majoră sau cazurile fortuite, așa cum sunt definite de Codul Civil Român. </p>
        <p>Trebuie să țineți cont că Produsele noastre sunt dispozitive mecanice și există riscuri inherent asociate utilizării acestora, inclusiv din cauza defecțiunilor, indiferent cât de bine sunt întreținute. Aceste riscuri nu sunt întotdeauna evidente și pot duce la daune materiale, vătămare corporală sau chiar decesul dvs. sau al altor persoane. Cu excepția cazurilor menționate mai sus, prin utilizarea Serviciilor noastre, sunteți de acord că înțelegeți aceste riscuri și că sunteți responsabil pentru utilizarea în condiții de siguranță a Serviciilor. De asemenea, sunteți responsabil pentru orice daune cauzate altor persoane sau proprietăți, cu excepția cazului în care ceea ce am făcut sau nu am făcut noi a fost cauza principală a acestor daune. </p>
        <h2>9. Responsabilitățile dumneavoastră </h2>
        <p>În conformitate cu legile aplicabile și așa cum este stabilit în Secțiunea 8 de mai sus, sunteți de acord să suportați toate pretențiile, acțiunile, costurile, daunele, penalitățile, amenzile, cerințele, pierderile, obligațiile și cheltuielile (inclusiv onorariile rezonabile ale avocaților și costurile judecătorești) care derivă din sau sunt legate de următoarele: </p>
        <p>Nerespectarea sau încălcarea acestor Termeni sau a oricăror legi aplicabile. </p>
        <p>Orice utilizare a conținutului furnizat de dvs. în conformitate cu Secțiunea 13. </p>
        <p>Încălcarea drepturilor dvs. de către orice terță parte. </p>
        <p>Vă asumați responsabilitatea pentru aceste obligații, iar această Secțiune 9 va rămâne în vigoare și după încetarea acestor Termeni, a contului dvs. de utilizator sau a accesului dvs. la Serviciile noastre în general. </p>
        <h2>10. Informațiile dvs. cu caracter personal </h2>
        <p>Nu colectăm și nu utilizăm informațiile dvs. cu caracter personal în scopul furnizării Serviciilor noastre.</p>
        <h2>11. Proprietatea intelectuală </h2>
        <p>Conform acestor Termeni, vă oferim o licență limitată, neexclusivă, nesublicențiată, revocabilă și netransferabilă pentru a accesa și utiliza Aplicația, software-ul și serviciile noastre asociate pe dispozitivul dvs. personal, cu condiția să le utilizați exclusiv în scop personal și non-comercial. Toate drepturile care nu sunt acordate în mod expres în prezentul document sunt păstrate de noi și de licențiatorii noștri. Nu vă este permis să copiați, să modificați, să distribuiți, să vindeți sau să închiriați nicio parte a Serviciilor sau a software-ului asociat, și nu aveți dreptul să efectuați inginerie inversă sau să încercați să extrageți codul sursă al Serviciilor sau al software-ului, cu excepția cazului în care legile interzic aceste restricții sau aveți permisiunea noastră scrisă în acest sens. Nu este permis să exercitați o presiune nerezonabilă asupra infrastructurii noastre prin utilizarea Serviciilor, să utilizați roboți, programe de tip spider, tehnici de scraping sau alte mijloace automate pentru a accesa Serviciile noastre, sau să încercați să interferați cu funcționarea corespunzătoare a Serviciilor noastre sau să evitați măsurile noastre de securitate pentru a accesa Serviciile. </p>
        <p>Proprietatea Serviciilor aparține exclusiv nouă, iar utilizarea acestora nu vă conferă niciun drept de proprietate. Utilizarea Serviciilor noastre nu vă conferă dreptul de a dobândi proprietatea asupra drepturilor de proprietate intelectuală asociate Serviciilor noastre sau conținutului la care aveți acces. Cu excepția licenței limitate acordate mai sus, toate drepturile (inclusiv drepturile de proprietate intelectuală) asupra acestora ne aparțin nouă sau licențiatorilor noștri. Nu aveți permisiunea de a utiliza mărci comerciale, branduri sau logo-uri utilizate în Serviciile noastre sau în alt mod, inclusiv în reclame sau publicitate, și nu aveți permisiunea de a sugera în vreun fel că suntem de acord cu sau susținem activitatea dvs. Vă rugăm să nu modificați sau să ascundeți nicio notificare legală afișată în, împreună cu sau în legătură cu Serviciile noastre. </p>
        <p></p>Proprietatea Serviciilor aparține exclusiv nouă, iar utilizarea acestora nu vă conferă niciun drept de proprietate. Utilizarea Serviciilor noastre nu vă conferă dreptul de a dobândi proprietatea asupra drepturilor de proprietate intelectuală asociate Serviciilor noastre sau conținutului la care aveți acces. Cu excepția licenței limitate acordate mai sus, toate drepturile (inclusiv drepturile de proprietate intelectuală) asupra acestora ne aparțin nouă sau licențiatorilor noștri. Nu aveți permisiunea de a utiliza mărci comerciale, branduri sau logo-uri utilizate în Serviciile noastre sau în alt mod, inclusiv în reclame sau publicitate, și nu aveți permisiunea de a sugera în vreun fel că suntem de acord cu sau susținem activitatea dvs. Vă rugăm să nu modificați sau să ascundeți nicio notificare legală afișată în, împreună cu sau în legătură cu Serviciile noastre. 
        <h2>12. Conținutul furnizat de dvs.</h2>
        <p>Este posibil să vi se solicite să ne trimiteți conținut, cum ar fi comentarii la postări pe blog, pentru a participa la comunitățile noastre sau pentru a oferi sfaturi utilizatorilor. Păstrați dreptul de proprietate asupra acestui conținut, însă asigurați-vă că aveți dreptul de a-l trimite, deoarece atunci când îl transmiteți, ne acordați (și partenerilor noștri) o licență nelimitată, gratuită și globală de a-l utiliza, găzdui, stoca, reproduce, modifica, crea lucrări derivate, comunica, publica, afișa public și distribui conținutul, precum și numele dvs., vocea și/sau înfățișarea, în măsura permisă de legislația aplicabilă. Această licență rămâne în vigoare chiar dacă încetați să utilizați Serviciile noastre. Feedback-ul sau sugestiile referitoare la Serviciile noastre pe care le trimiteți pot fi utilizate de noi fără a avea obligația de a vă compensa. Vă rugăm să rețineți că orice conținut pe care îl trimiteți este considerat non-confidențial. </p>
        <p>Vă solicităm să nu trimiteți conținut defăimător, calomniator, plin de ură, violent, obscen, pornografic, ilegal sau în alt mod ofensator (decizia de a determina dacă conținutul îndeplinește aceste criterii aparține nouă). La fel se aplică și pentru publicitatea "spam" sau nesolicitată. Transmiterea unui astfel de conținut poate duce la suspendarea sau rezilierea contului dvs. de utilizator, inclusiv în cazurile impuse de lege. Avem dreptul, dar nu și obligația, de a verifica, monitoriza sau elimina conținutul dvs. în orice moment, indiferent de motiv, fără notificare prealabilă, în conformitate cu legislația aplicabilă. </p>
        <h2>13. Serviciile și conținutul părților terțe </h2>
        <p>Serviciile pot fi puse la dispoziție sau accesate în legătură cu servicii și conținut (inclusiv reclame) controlate de terțe părți, care pot avea termeni de utilizare și politici de confidențialitate diferite. Trebuie să știți că noi nu avem nicio susținere oficială pentru aceste servicii și conținuturi ale terțelor părți, și nu ne asumăm responsabilitatea sau răspunderea pentru produsele sau serviciile lor. </p>
        <p>În plus, atunci când accesați Serviciile utilizând aplicații dezvoltate pentru platforme precum Apple iOS, Android, Microsoft Windows sau dispozitive mobile cu tehnologie Blackberry, trebuie să țineți cont că Apple Inc., Google, Inc., Microsoft Corporation și/sau Blackberry Limited pot fi considerați beneficiari terți ai acestor Termeni. Cu toate acestea, acești beneficiari terți nu sunt parte a acestor Termeni și nu au nicio responsabilitate în ceea ce privește furnizarea sau asistența pentru Servicii în niciun fel. Dreptul dvs. de acces la Servicii, utilizând aceste aplicații sau dispozitive, este supus termenilor și condițiilor de utilizare și politicilor de confidențialitate aplicabile ale acestor terțe părți respective. </p>
        <h2>14. Accesul la rețea și dispozitive </h2>
        <p>Este responsabilitatea dvs. să vă asigurați că aveți acces la o rețea de date necesară pentru a utiliza Serviciile. Dacă accesați sau utilizați Serviciile de pe dispozitivul dvs., este posibil să vi se aplice tarife și comisioane de date și mesaje din partea furnizorului dvs. de servicii mobile. </p>
        <p>Trebuie să vă asigurați că achiziționați și actualizați echipamentele hardware sau dispozitivele compatibile necesare pentru a accesa și utiliza Serviciile, inclusiv Aplicația, și pentru a instala orice actualizări necesare. Trebuie să rețineți că nu putem garanta că Serviciile sau oricare dintre componentele lor vor funcționa pe orice echipament sau dispozitiv specific. De asemenea, trebuie să luați în considerare că utilizarea Internetului și comunicațiilor electronice poate suferi defecțiuni și întârzieri inerente. </p>
        <h2>15. Aspecte generale</h2>
        <p>Nu aveți dreptul să transferați acești Termeni fără a obține în prealabil aprobarea noastră scrisă. Noi, pe de altă parte, putem atribui acești Termeni unei entități afiliate, asociate sau în cazul unei vânzări a activelor noastre, a acțiunilor sau a activității noastre comerciale sau unui succesor prin fuziune, fără a fi nevoie de consimțământul dvs. Orice încercare de cesionare care contravine acestui paragraf va fi considerată nulă. </p>
        <p>Nu există nicio înțelegere de tip asociere în participațiune, parteneriat, sau o relație de angajare sau reprezentare între dvs. și noi, în baza acestor Termeni sau a utilizării Serviciilor noastre. </p>
        <p>Dacă oricare dintre prevederile acestor Termeni este declarată nulă sau neaplicabilă, acea prevedere va fi eliminată, iar celelalte prevederi vor rămâne în vigoare în măsura în care permite legea. Faptul că nu ne folosim de un anumit drept sau prevedere din acești Termeni într-un anumit moment nu înseamnă o renunțare la respectivul drept sau prevedere, cu excepția cazului în care o admitem și acordăm în scris, și nu constituie o renunțare la dreptul nostru de a face acest lucru în viitor. </p>
        <p>Evenimentele de forță majoră pot să ne împiedice să furnizăm Serviciile. Vă rugăm să rețineți că atunci când utilizăm termenii "include" sau "includerea" în acești Termeni, aceasta înseamnă de fapt "inclusiv, dar fără a se limita la", cu scopul de a ușura citirea. Dispozițiile care, din natura lor, trebuie să rămână valabile și după încetarea acestor Termeni sau după încetarea utilizării Serviciilor, vor rămâne în vigoare și după aceea. </p>
        <h2>16. Litigii</h2>
        <p>Acești Termeni vor fi supuși legii din România. Dacă apare un litigiu legat de acești Termeni, care nu poate fi rezolvat în alt mod, puteți opta să utilizați Platforma europeană de soluționare online a litigiilor, disponibilă la adresa http://ec.europa.eu/consumers/odr/, pentru a afla mai multe despre alternativele de rezolvare a conflictelor.</p>
        <p className="bold final">Prin aceasta, confirm că am cel puțin 18 ani și că am citit și sunt în total acord cu termenii și condițiile stabilite în acești Termeni.</p>
    </div>
  )
}

export default Terms